name: example
description: example for tdmarkup_dart
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  url_launcher: ^5.7.10
  tdmarkup_dart:
    path: ../

dev_dependencies:
  pedantic: ^1.9.2

flutter:
  assets:
    - assets/example_message.json
