name: tdmarkup_dart
description: Widgets and view models to convert markup from Tada server into formatted text on the screen.
homepage: https://github.com/tada-team/tdmarkup_dart
repository: https://github.com/tada-team/tdmarkup_dart
issue_tracker: https://github.com/tada-team/tdmarkup_dart/issues

version: 1.0.0-dev+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  dart_extensions: ^1.0.2
  equatable: ^1.2.5
  characters: ^1.0.0
  meta: ^1.2.4

  tdproto_dart: ^1.0.1-dev

dev_dependencies:
  pedantic: ^1.9.2
