name: tdmarkup_dart
description: Tada flutter markup.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  dart_extensions: ^1.0.2
  equatable: ^1.2.5
  characters: ^1.0.0

  tdproto_dart: ^1.0.1-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
