name: tdmarkup
description: Tada flutter markup.
version: 0.0.1
author: eboshare

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tdproto_dart:
    git:
      url: https://github.com/tada-team/tdproto_dart.git
      ref: cffbd0bd  # dev branch
  intl: ^0.16.1
  dart_extensions: ^1.0.2
  equatable: ^1.2.5
  characters: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
